services:
  postgres:
    image: postgres:16-alpine
    container_name: movieflix_db
    environment:
      POSTGRES_DB: movieflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always